### PR TITLE
Changes for Jenkins integration

### PR DESCRIPTION
**Pull request by benclark**
Relevant changes in this PR:

1. Switched to inspec verifier (from serverspec). Inspec allows us to set output formatter to JUnit XML for integrating with Jenkins.
2. Rewrote the Rakefile and added a `jenkins` task.
3. Removed Travis integration, since our Jenkins instance will perform the same tasks.

### CODE REVIEW

**Comment by JacksonRiverDeploy** [comment]
Test comment

**Comment by JacksonRiverDeploy** [comment]
Test comment #2

**Comment by benclark** [comment]
Test comment.

**Comment by benclark** [comment]
Test comment 2.

**Pull request merged**
